theme: jekyll-theme-slate
title: Haibin Zhao
description: Hello everyone, I am currently a PhD Candidate at KIT, Helmholtz Association, under the supervision of Prof. Dr.-Ing. Michael Beigl. My research interests are Sensor Fusion, Indoor Localization, and Ubiquitous Computing.

